language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      env: IMAGE=coryan/jaybeamsdev-ubuntu16.04 COMPILER=g++ CXXFLAGS=-O3

#    - os: linux
#      compiler: gcc
#      env: IMAGE=coryan/jaybeamsdev-ubuntu14.04 COMPILER=g++ CXXFLAGS="-O0 -g -coverage" COVERAGE=yes

#    - os: linux
#      compiler: gcc
#      env: IMAGE=coryan/jaybeamsdev-fedora23 COMPILER=clang++ CXXFLAGS=-g GENDOCS=yes

#    - os: linux
#      compiler: gcc
#      env: IMAGE=coryan/jaybeamsdev-fedora23 COMPILER=clang++ CXXFLAGS=-O3

services:
  - docker

script:
  - uname -a
  - docker build --help
  - echo IMAGE=${IMAGE} CXX=${CXX} CXXFLAGS=${CXXFLAGS}
  - echo GENDOCS=${GENDOCS} CONFIGUREFLAGS=${CONFIGUREFLAGS}
  - echo HOME=$HOME USER=$USER UID=$UID
  - docker pull ${IMAGE?}
  - /usr/bin/env ${COMPILER?} --version
  - docker run --rm -it --env CXX=${COMPILER?} --env CXXFLAGS="${CXXFLAGS}" -v $PWD:$PWD ${IMAGE?} /bin/sh -c "cd $PWD && ./bootstrap && ./configure ${CONFIGUREFLAGS} && make -j 2 check"
  - cat test-suite.log || echo "Could not print test logs"

install:
  - if [ "x${COVERAGE}" = "xyes" ]; then gem install coveralls-lcov ; fi

after_success:
  # We take some additional action on successful builds ...
  - cd ${TRAVIS_BUILD_DIR?}
  # ... if this is a code coverage build we upload the coverage results ...
  - if [ "x$TRAVIS_PULL_REQUEST" == "xfalse" -a "x${COVERAGE}" = "xyes" ]; then
    docker run --rm -it -v $PWD:$PWD ${IMAGE?} /bin/sh -c "cd $PWD && ci/coverage.sh" ;
    coveralls-lcov --repo-token ${COVERALLS_TOKEN?} coverage.info ;
    fi
  # ... if this is a documentation build we generate the docs ...
  - if [ "x${TRAVIS_BRANCH}" != "xmaster" ]; then GENDOCS=no ; fi
  # ... create the Doxygen documentation inside the docker container,
  # and then push it using the host ...
  - if [ "x$TRAVIS_PULL_REQUEST" == "xfalse" -a "x${GENDOCS}" == "xyes" ]; then
    docker run --rm -it --env GIT_NAME=${GIT_NAME?} --env GIT_EMAIL=${GIT_EMAIL?} -v $PWD:/home/${USER?}/jaybeams ${IMAGE?} /bin/sh -c "cd /home/${USER?}/jaybeams && ci/gendocs.sh" ;
    (cd doc/html ; git push https://${GH_TOKEN?}@github.com/coryan/jaybeams gh-pages) ;
    fi

notifications:
  email: false
