language: cpp

os:
  - linux

before_install:
  - echo PWD = $PWD
  - echo COMPILER=${COMPILER} VERSION=${VERSION} VARIANT=${VARIANT} GENDOCS=${GENDOCS}
# ... first install a utility to quickly modify the apt sources ...
  - sudo apt-get -qq -y install python-software-properties
# ... this PPA contains backports of gcc and the related tools ...
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
# ... this PPA contains backports of many GNU tools, including
# automake and autoconf ...
  - sudo add-apt-repository -y ppa:dns/gnu
# ... this PPA contains backports of the Boost libraries, as of this
# writing they are on 1.55 while Boost just released 1.59.  The 1.55
# version is enough for me though ...
  - sudo add-apt-repository -y ppa:boost-latest/ppa
# ... these are the common toolchain utilities for clang and llvm ...
  - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main"
# ... here is the version of clang ...
  - sudo add-apt-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main"
# ... we need to install the public GPG keys from the llvm.org folks ...
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
# ... update the apt information after all the modifications are done ...
  - sudo apt-get -qq update

install:
# ... all dependencies are installed from the $HOME/deps directory, to
# keep the source clean ...
  - (mkdir ${HOME?}/deps && cd ${HOME?}/deps && ${TRAVIS_BUILD_DIR?}/ci/install.sh)

before_script:
  - echo COMPILER=${COMPILER} VERSION=${VERSION} VARIANT=${VARIANT} GENDOCS=${GENDOCS}
  - cd ${TRAVIS_BUILD_DIR?}
  - source ci/before_script.sh
  - if [ "x${VARIANT}" == "xcov" ]; then lcov --directory . --zerocounters; fi

script:
  - echo CXX=${CXX?} CXXFLAGS=${CXXFLAGS?} GENDOCS=${GENDOCS?}
  - ${CXX?} --version
  - echo ${CXXFLAGS?}
  - ./bootstrap
  - ./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu
  - make
  - make check

after_success:
# Upload code coverage results to coveralls.io
  - cd ${TRAVIS_BUILD_DIR?}
  - if [ "x${VARIANT?}" == "xcov" ]; then ci/coverage.sh; fi
# Upload documentation to gh-pages
  - if [ "x${GENDOCS?}" == "xyes" ]; then ci/gendocs.sh; fi

notifications:
  email: false

env:
  matrix:
#   - COMPILER=gcc   VERSION=-4.9  VARIANT=opt  GENDOCS=no
   - COMPILER=gcc   VERSION=-4.9  VARIANT=cov  GENDOCS=no
   - COMPILER=clang VERSION=-3.6  VARIANT=dbg  GENDOCS=yes
#   - COMPILER=clang VERSION=-3.6  VARIANT=opt  GENDOCS=no
  global:
# TODO(#1) change this to a robot account
    - secure: "n9xlk1SpwtyBBB/U3B+o7EQomk4wPS+lj+9pYQCJwLkmR4Yh6hoz/bsl5vlYYK1V6xFhAaXqPWBnQmhrsIf8lOWqqrKCOPFsJ1AxDgPY3zFt+G91BqOuaTSG2eCbnyEVPidBchaUTeg2NiOpCAHyzA17h65c1Hl4l6IBUWGpYft5MWZhkeYz5r0bP2KAIb2NWRhuAW3PYxmFArWhBpnTICMx7rXzYWYCPUiXYra2JNebS1JAp+4JPly0efvNNjtjv4dyxq8qMdTDgz5Kj9wGo8ByPpseyWgx5Il0SSHmeUN5/NhJj4Wx2lVjOSv/EfoFmDN86V+P2zCwkl0tKV8sYONNvAIDqPDadRfQhbUAAFidSYiS2O6ttbInxegs3jStus/jxD0Myn8BgvOgddPbe1p0WFhCtcPDPA5J9/ic8M1NclYlMp04QNED+PnxxVt94tTmU7zCsNGXX4rxa7B1Q4EjTvEmjtvPA99kBla8JGOOxws8Xo5+WkfWVfbinveqs6G3kqg2bKTcurvgCeT7gqc/uVymdti7xdn+xALfzSohH91qN/T0Md1NVBJOlIN+J6oQ+qmZMcTQ6RrPOKDKPqcFTgpp5Np/lvq0yMUL7s+rS544hXZvtZ96E25wCorbJv6DVl0m5D1crBsJGmMzYfcGtRc8smTpF4+YcRkUIfc="
