JayBeams: jb::fftw::time_delay_estimator_many< array_t, multi_array > Class Template Reference
jb::fftw::time_delay_estimator_many< array_t, multi_array > Class Template Reference
A simple time delay estimator based on cross-correlation.
#include <time_delay_estimator_many.hpp>
Public Types
Type traits
using array_type = array_t
The input timeseries type.
using element_type = typename jb::detail::array_traits< array_type >::element_type
The values stored in the input timeseries.
using precision_type = typename jb::extract_value_type< element_type >::precision
Extract T out of std::complex<T>, otherwise simply T.
using frequency_array_type = multi_array< std::complex< precision_type >, array_type::dimensionality >
The type used to store the DFT of the input timeseries.
using output_array_type = multi_array< precision_type, array_type::dimensionality >
The type used to store the inverse of the DFT.
using dplan = jb::fftw::plan< array_type, frequency_array_type >
The execution plan to apply the (forward) DFT.
using iplan = jb::fftw::plan< frequency_array_type, output_array_type >
The execution plan to apply the inverse (aka backward) DFT.
using confidence_type = jb::fftw::tde_result< array_t, precision_type >
The type used to store the TDE confidence between two timeseries.
using argmax_type = jb::fftw::tde_result< array_t, std::size_t >
The type used to store the TDE argmax between two timeseries.
using sum2_type = jb::fftw::tde_result< array_t, precision_type >
The sqr sum of a timeseries.
Public Member Functions
time_delay_estimator_many (array_type const &a, array_type const &b)
Constructs members using the multi array characteristic a and b.
void estimate_delay (array_type const &a, array_type const &b, sum2_type const &sum2, confidence_type &confidence, argmax_type &argmax)
Compute the time-delay estimate between two timeseries a and b.
Static Private Member Functions
static int planning_flags ()
Determine the correct FFTW planning flags given the inputs.
Private Attributes
frequency_array_type tmpa_
tmpa_ : timeseries to store the result of FFT(a)
frequency_array_type tmpb_
tmpb_ : timeseries to store the result of FFT(b)
dplan a2tmpa_
a2tmpa_ : fftw plan to execute FFT(a)
dplan b2tmpb_
b2tmpb_ : fftw plan to execute FFT(b)
output_array_type out_
out_ : timeseries to store the result of inverse FFT
iplan tmpa2out_
tmpa2out : fftw plan to execute inverse FFT of a timeseries
std::size_t nsamples_
nsamples : num samples of timeseries
std::size_t num_timeseries_
num_timeseries : num of timeseries contained in a and b
Detailed Description
template<typename array_t, template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array>
class jb::fftw::time_delay_estimator_many< array_t, multi_array >
A simple time delay estimator based on cross-correlation.
Timeseries are implemented as aligned multi arrays of N dimensions
Template Parameters
array_t timeseries multi array type
T timeseries value type
K timeseries dimensionality
Definition at line 25 of file time_delay_estimator_many.hpp.
Member Typedef Documentation
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::argmax_type = jb::fftw::tde_result<array_t, std::size_t>
The type used to store the TDE argmax between two timeseries.
Definition at line 61 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::array_type = array_t
The input timeseries type.
Definition at line 33 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::confidence_type = jb::fftw::tde_result<array_t, precision_type>
The type used to store the TDE confidence between two timeseries.
Definition at line 58 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::dplan = jb::fftw::plan<array_type, frequency_array_type>
The execution plan to apply the (forward) DFT.
Definition at line 52 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::element_type = typename jb::detail::array_traits<array_type>::element_type
The values stored in the input timeseries.
Definition at line 37 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::frequency_array_type = multi_array<std::complex<precision_type>, array_type::dimensionality>
The type used to store the DFT of the input timeseries.
Definition at line 45 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::iplan = jb::fftw::plan<frequency_array_type, output_array_type>
The execution plan to apply the inverse (aka backward) DFT.
Definition at line 55 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::output_array_type = multi_array<precision_type, array_type::dimensionality>
The type used to store the inverse of the DFT.
Definition at line 49 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::precision_type = typename jb::extract_value_type<element_type>::precision
Extract T out of std::complex<T>, otherwise simply T.
Definition at line 41 of file time_delay_estimator_many.hpp.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> using jb::fftw::time_delay_estimator_many< array_t, multi_array >::sum2_type = jb::fftw::tde_result<array_t, precision_type>
The sqr sum of a timeseries.
Definition at line 64 of file time_delay_estimator_many.hpp.
Constructor & Destructor Documentation
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many (array_type const & a, array_type const & b) inline
Constructs members using the multi array characteristic a and b.
Parameters
a multi array timeries
b multi array timeries
Definition at line 76 of file time_delay_estimator_many.hpp.
References jb::fftw::time_delay_estimator_many< array_t, multi_array >::a2tmpa_, jb::detail::array_shape(), jb::fftw::time_delay_estimator_many< array_t, multi_array >::b2tmpb_, jb::fftw::create_backward_plan(), jb::fftw::create_forward_plan(), jb::detail::element_count(), jb::detail::nsamples(), jb::fftw::time_delay_estimator_many< array_t, multi_array >::nsamples_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::num_timeseries_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::out_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::planning_flags(), jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpa2out_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpa_, and jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpb_.
Member Function Documentation
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> void jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay (array_type const & a, array_type const & b, sum2_type const & sum2, confidence_type & confidence, argmax_type & argmax) inline
Compute the time-delay estimate between two timeseries a and b.
Parameters
a input timeseries
b input timeseries
sum2 contains sqr sum of one of the timeseries (a or b)
confidence to return the confidence of the TDE(a,b)
argmax to return argmax TDE(a,b)
Definition at line 99 of file time_delay_estimator_many.hpp.
References jb::fftw::time_delay_estimator_many< array_t, multi_array >::a2tmpa_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::b2tmpb_, jb::testing::close_enough(), jb::fftw::plan< in_timeseries_type, out_timeseries_type >::execute(), jb::fftw::time_delay_estimator_many< array_t, multi_array >::nsamples_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::num_timeseries_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::out_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpa2out_, jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpa_, and jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpb_.
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> static int jb::fftw::time_delay_estimator_many< array_t, multi_array >::planning_flags () inline static private
Determine the correct FFTW planning flags given the inputs.
Definition at line 143 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
Member Data Documentation
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> dplan jb::fftw::time_delay_estimator_many< array_t, multi_array >::a2tmpa_ private
a2tmpa_ : fftw plan to execute FFT(a)
Definition at line 156 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> dplan jb::fftw::time_delay_estimator_many< array_t, multi_array >::b2tmpb_ private
b2tmpb_ : fftw plan to execute FFT(b)
Definition at line 158 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> std::size_t jb::fftw::time_delay_estimator_many< array_t, multi_array >::nsamples_ private
nsamples : num samples of timeseries
Definition at line 164 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> std::size_t jb::fftw::time_delay_estimator_many< array_t, multi_array >::num_timeseries_ private
num_timeseries : num of timeseries contained in a and b
Definition at line 166 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> output_array_type jb::fftw::time_delay_estimator_many< array_t, multi_array >::out_ private
out_ : timeseries to store the result of inverse FFT
Definition at line 160 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> iplan jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpa2out_ private
tmpa2out : fftw plan to execute inverse FFT of a timeseries
Definition at line 162 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> frequency_array_type jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpa_ private
tmpa_ : timeseries to store the result of FFT(a)
Definition at line 152 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
template<typename array_t , template< typename T, std::size_t K > class multi_array = jb::fftw::aligned_multi_array> frequency_array_type jb::fftw::time_delay_estimator_many< array_t, multi_array >::tmpb_ private
tmpb_ : timeseries to store the result of FFT(b)
Definition at line 154 of file time_delay_estimator_many.hpp.
Referenced by jb::fftw::time_delay_estimator_many< array_t, multi_array >::estimate_delay(), and jb::fftw::time_delay_estimator_many< array_t, multi_array >::time_delay_estimator_many().
The documentation for this class was generated from the following file:
jb/fftw/time_delay_estimator_many.hpp