JayBeams: jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t > Class Template Reference
jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t > Class Template Reference
Handles TDE result for a multi array type timeseries.
#include <tde_result.hpp>
Public Types
using value_type = value_t
using array_type = jb::fftw::aligned_multi_array< T, K >
using record_type = jb::fftw::aligned_multi_array< value_type, K-1 >
Public Member Functions
tde_result (array_type const &a)
value_type & operator[] (std::size_t pos)
value_type const & operator[] (std::size_t pos) const
std::size_t size () const
Private Attributes
record_type record_
std::size_t size_
Detailed Description
template<typename T, std::size_t K, typename value_t>
class jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >
Handles TDE result for a multi array type timeseries.
Template Parameters
T type of the value stored on the timeseries
K timeseries dimensionality
value_t type to store the result of the timeseries operation
Definition at line 57 of file tde_result.hpp.
Member Typedef Documentation
template<typename T , std::size_t K, typename value_t > using jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::array_type = jb::fftw::aligned_multi_array<T, K>
Definition at line 60 of file tde_result.hpp.
template<typename T , std::size_t K, typename value_t > using jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::record_type = jb::fftw::aligned_multi_array<value_type, K - 1>
Definition at line 62 of file tde_result.hpp.
template<typename T , std::size_t K, typename value_t > using jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::value_type = value_t
Definition at line 59 of file tde_result.hpp.
Constructor & Destructor Documentation
template<typename T , std::size_t K, typename value_t > jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::tde_result (array_type const & a) inline
Definition at line 64 of file tde_result.hpp.
References jb::detail::array_shape(), jb::detail::element_count(), jb::detail::nsamples(), and jb::fftw::tde_result< container_t, value_t >::size_.
Member Function Documentation
template<typename T , std::size_t K, typename value_t > value_type& jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::operator[] (std::size_t pos) inline
Definition at line 69 of file tde_result.hpp.
template<typename T , std::size_t K, typename value_t > value_type const& jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::operator[] (std::size_t pos) const inline
Definition at line 72 of file tde_result.hpp.
template<typename T , std::size_t K, typename value_t > std::size_t jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::size () const inline
Definition at line 75 of file tde_result.hpp.
References jb::fftw::tde_result< container_t, value_t >::size_.
Member Data Documentation
template<typename T , std::size_t K, typename value_t > record_type jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::record_ private
Definition at line 80 of file tde_result.hpp.
template<typename T , std::size_t K, typename value_t > std::size_t jb::fftw::tde_result< jb::fftw::aligned_multi_array< T, K >, value_t >::size_ private
Definition at line 81 of file tde_result.hpp.
The documentation for this class was generated from the following file:
jb/fftw/tde_result.hpp