JayBeams: jb::itch5::array_based_book_side< compare_t > Class Template Reference
jb::itch5::array_based_book_side< compare_t > Class Template Reference
Represent one side of the book.
#include <array_based_order_book.hpp>
Public Member Functions
array_based_book_side (std::size_t sz)
half_quote empty_quote () const
half_quote best_quote () const
half_quote worst_quote () const
std::size_t count () const
bool add_order (price4_t px, int qty)
Add a price and quantity to the side order book.
bool reduce_order (price4_t px, int qty)
Reduce the quantity for a given price.
bool check_better (price4_t const &px1, price4_t const &px2) const
Testing hook.
auto get_limits () const
Testing hook.
auto get_counts () const
Testing hook.
auto test_price_to_relative (price4_t const &px) const
Testing hooks to increase coverage.
auto test_relative_worst_top_level () const
void test_move_top_to_bottom (price4_t const &px)
Static Public Member Functions
static half_quote empty_bid ()
The value used to represent an empty bid.
static half_quote empty_offer ()
The value used to represent an empty offer.
Private Member Functions
price4_t relative_to_price (int rel) const
Transforms a top_levels_ relative position into an absolute price.
price4_t relative_above_base (price4_t const &px_base, int const rel_tick) const
price4_t relative_below_base (price4_t const &px_base, int const rel_tick) const
std::size_t price_to_relative (price4_t const &px) const
Transforms an absolute price into a top_levels_ relative position.
std::size_t relative_worst_top_level () const
std::size_t top_levels_count () const
auto get_limit_top_prices (price4_t const &px) const
void move_top_to_bottom (price4_t const px_max)
Move prices from px_begin_top_ to px_max (excluded) out of top_levels_ to bottom_levels_.
void move_bottom_to_top ()
Move relative prices from best price to px_begin_top* (included) out of bottom_levels_ to top_levels_.
price4_t next_best_price () const
Private Attributes
compare_t better_
function object for inequality comparison of template parameter type.
std::size_t max_size_
top_levels_ max size
std::vector< int > top_levels_
the best relative prices and quantity
std::map< price4_t, int, compare_t > bottom_levels_
the worst (tail) absolute prices and quantity
price4_t px_inside_
better absolute price of top_levels_ range
price4_t px_begin_top_
one absolute price past-the-worst price in top_levels_ range
price4_t px_end_top_
absolute price at the inside
Detailed Description
template<typename compare_t>
class jb::itch5::array_based_book_side< compare_t >
Represent one side of the book.
Class implementation of struct array_based_order_book buy and side types.
Template Parameters
compare_t function object class type to sort the side
top_levels_ variables notation and definition:
px_X : price4_t type. An actual price.
px_1 = price4_t(100000), price is $10.00
px_2 = price4_t(5000), price is c50 (fifty cents)
tk_X : int type. A price level. First 10000 are mill, then penny.
tk_1 = 5010, price is c50.10
tk_2 = 10005, price is $1.05 ($1.00 + 5 penny)
rel_X : size_t type. A relative position of a price at top_levels_
BUY side examples:
rel_1 = 20 (with px_begin_top_ = $30.00), tk_1 = 12920, px_1 = $30.20
rel_2 = 40 (with px_begin_top_ = c30.00), tk_2 = 3040, px_2 = c30.40
rel_3 = 1020 (with px_begin_top_ = c90.00), tk_3 = 10020, px_3 = $1.20
SELL side examples :
rel_1 = 20 (with px_begin_top_ = $30.00), tk_1 = 12880, px_1 = $29.80
rel_2 = 40 (with px_begin_top_ = c30.00), tk_2 = 2960, px_2 = c29.60
rel_3 = 1020 (with px_begin_top_ = $1.10), tk_3 = 8990, px_3 = c89.90
Definition at line 56 of file array_based_order_book.hpp.
Constructor & Destructor Documentation
template<typename compare_t > jb::itch5::array_based_book_side< compare_t >::array_based_book_side (std::size_t sz) inline explicit
Definition at line 58 of file array_based_order_book.hpp.
Member Function Documentation
template<typename compare_t > bool jb::itch5::array_based_book_side< compare_t >::add_order (price4_t px, int qty) inline
Add a price and quantity to the side order book.
Parameters
px the price of the new order
qty the quantity of the new order
Returns
true if the inside changed
Validates:
if px is off limits (<= empty_bid price or >= empty_offer price)
if qty <= 0
throws an exception if this is the case
Then:
if px is worse than the px_begin_top_ then px goes to bottom_levels
if px is better than the inside then changes inside, redefines limits if needed (moving the tail to bottom_levels if any)
finally, updates qty at the relative(px)
Definition at line 145 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::array_based_book_side< compare_t >::bottom_levels_, jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices(), jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::px_begin_top_, jb::itch5::array_based_book_side< compare_t >::px_end_top_, jb::itch5::array_based_book_side< compare_t >::px_inside_, and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename compare_t > half_quote jb::itch5::array_based_book_side< compare_t >::best_quote () const inline
Returns
the best bid price and quantity. The inside is always at the top_levels_ (empty_quote.price when empty)
Definition at line 91 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::empty_quote(), jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::px_inside_, and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename compare_t > bool jb::itch5::array_based_book_side< compare_t >::check_better (price4_t const & px1, price4_t const & px2) const inline
Testing hook.
Returns
true is px1 < px2 To test different implementations for buy and sell sides
Definition at line 305 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_.
template<typename compare_t > std::size_t jb::itch5::array_based_book_side< compare_t >::count () const inline
Returns
the number of levels with non-zero quantity for the order side. This is the size of bottom_levels_ plus all non zero top_levels values
Definition at line 120 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::bottom_levels_, and jb::itch5::array_based_book_side< compare_t >::top_levels_count().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename compare_t > static half_quote jb::itch5::array_based_book_side< compare_t >::empty_bid () inline static
The value used to represent an empty bid.
Definition at line 69 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::empty_quote().
template<typename compare_t > static half_quote jb::itch5::array_based_book_side< compare_t >::empty_offer () inline static
The value used to represent an empty offer.
Definition at line 74 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::empty_quote().
template<typename compare_t > half_quote jb::itch5::array_based_book_side< compare_t >::empty_quote () const inline
Returns
an empty bid or offer based on compare function empty bid for less, empty offer for greater.
Definition at line 80 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::array_based_book_side< compare_t >::empty_bid(), and jb::itch5::array_based_book_side< compare_t >::empty_offer().
Referenced by jb::itch5::array_based_book_side< compare_t >::best_quote(), jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices(), jb::itch5::array_based_book_side< compare_t >::next_best_price(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), jb::itch5::array_based_book_side< compare_t >::top_levels_count(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
template<typename compare_t > auto jb::itch5::array_based_book_side< compare_t >::get_counts () const inline
Testing hook.
Returns
{bottom_levels_ size , top_levels_ size}
Definition at line 319 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::bottom_levels_, and jb::itch5::array_based_book_side< compare_t >::top_levels_count().
Referenced by BOOST_AUTO_TEST_CASE().
template<typename compare_t > auto jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices (price4_t const & px) const inline private
Returns
pair of absolute prices that are max_size/2 worse and better than px, limited to valid prices if px is at the limit, return and empty quote values
Definition at line 462 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::array_based_book_side< compare_t >::empty_quote(), jb::itch5::array_based_book_side< compare_t >::max_size_, jb::itch5::array_based_book_side< compare_t >::relative_above_base(), and jb::itch5::array_based_book_side< compare_t >::relative_below_base().
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), and jb::itch5::array_based_book_side< compare_t >::reduce_order().
template<typename compare_t > auto jb::itch5::array_based_book_side< compare_t >::get_limits () const inline
Testing hook.
Returns
{px_begin_top_, px_end_top_}
Definition at line 312 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::px_begin_top_, and jb::itch5::array_based_book_side< compare_t >::px_end_top_.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename compare_t > void jb::itch5::array_based_book_side< compare_t >::move_bottom_to_top () inline private
Move relative prices from best price to px_begin_top* (included) out of bottom_levels_ to top_levels_.
*px_begin_top_ is updated before calling this function.
Definition at line 542 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::array_based_book_side< compare_t >::bottom_levels_, jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::px_begin_top_, and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by jb::itch5::array_based_book_side< compare_t >::reduce_order().
template<typename compare_t > void jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom (price4_t const px_max) inline private
Move prices from px_begin_top_ to px_max (excluded) out of top_levels_ to bottom_levels_.
Parameters
px_max first limit price that is not moved out.
Validates that px_max is in range (better or equal to px_begin_top_) Inserts the prices into bottom_levels_ Shift top_levels_ prices in order for rel_max to become relative 0 Clear (value = 0) former relative position of moved prices
Definition at line 489 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::array_based_book_side< compare_t >::bottom_levels_, jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::px_begin_top_, jb::itch5::array_based_book_side< compare_t >::px_inside_, jb::itch5::array_based_book_side< compare_t >::relative_to_price(), and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), and jb::itch5::array_based_book_side< compare_t >::test_move_top_to_bottom().
template<typename compare_t > price4_t jb::itch5::array_based_book_side< compare_t >::next_best_price () const inline private
Returns
the best next price from the inside. (return empty quote price if none available).
Definition at line 566 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::empty_quote(), jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::px_inside_, jb::itch5::array_based_book_side< compare_t >::relative_to_price(), and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by jb::itch5::array_based_book_side< compare_t >::reduce_order().
template<typename compare_t > std::size_t jb::itch5::array_based_book_side< compare_t >::price_to_relative (price4_t const & px) const inline private
Transforms an absolute price into a top_levels_ relative position.
px has to be better or equal to px_begin_top_
Parameters
px an absolute price
Returns
top_levels_ relative position of px compare with px_begin_top_
Definition at line 413 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::price_levels(), and jb::itch5::array_based_book_side< compare_t >::px_begin_top_.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::best_quote(), jb::itch5::array_based_book_side< compare_t >::move_bottom_to_top(), jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::next_best_price(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), jb::itch5::array_based_book_side< compare_t >::test_price_to_relative(), and jb::itch5::array_based_book_side< compare_t >::top_levels_count().
template<typename compare_t > bool jb::itch5::array_based_book_side< compare_t >::reduce_order (price4_t px, int qty) inline
Reduce the quantity for a given price.
Parameters
px the price of the order that was reduced
qty the quantity reduced in the order
Returns
true if the inside changed
Validates a positive qty Checks and handles if px is a bottom_level_ price Checks if top_levels_ is empty after reducing If so, limits have to be redefined, and tail moved into top_levels
Definition at line 200 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::array_based_book_side< compare_t >::bottom_levels_, jb::itch5::array_based_book_side< compare_t >::empty_quote(), jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices(), JB_LOG, jb::itch5::array_based_book_side< compare_t >::move_bottom_to_top(), jb::itch5::array_based_book_side< compare_t >::next_best_price(), jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::px_begin_top_, jb::itch5::array_based_book_side< compare_t >::px_end_top_, jb::itch5::array_based_book_side< compare_t >::px_inside_, jb::itch5::array_based_book_side< compare_t >::top_levels_, and jb::warning.
Referenced by BOOST_AUTO_TEST_CASE().
template<typename compare_t > price4_t jb::itch5::array_based_book_side< compare_t >::relative_above_base (price4_t const & px_base, int const rel_tick) const inline private
Parameters
px_base base absolute price
rel_tick price levels above px_base
Returns
absolute price rel_tick price levels above px_base
Definition at line 356 of file array_based_order_book.hpp.
References jb::itch5::price_field< wire_type_t, denom_v >::as_integer(), jb::itch5::price_levels(), and jb::itch5::WIRE_MAX.
Referenced by jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices(), and jb::itch5::array_based_book_side< compare_t >::relative_to_price().
template<typename compare_t > price4_t jb::itch5::array_based_book_side< compare_t >::relative_below_base (price4_t const & px_base, int const rel_tick) const inline private
Parameters
px_base absolute base price
rel_tick price levels below px_base
Returns
an absolute price that is rel_tick price levels below px_base
Definition at line 383 of file array_based_order_book.hpp.
References jb::itch5::price_field< wire_type_t, denom_v >::as_integer(), jb::itch5::price_levels(), and jb::itch5::TK_DOLLAR.
Referenced by jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices().
template<typename compare_t > price4_t jb::itch5::array_based_book_side< compare_t >::relative_to_price (int rel) const inline private
Transforms a top_levels_ relative position into an absolute price.
Parameters
rel relative position of a price at top_levels_
Returns
the absolute price
Definition at line 343 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::better_, jb::itch5::array_based_book_side< compare_t >::max_size_, jb::itch5::array_based_book_side< compare_t >::px_begin_top_, jb::itch5::array_based_book_side< compare_t >::px_end_top_, and jb::itch5::array_based_book_side< compare_t >::relative_above_base().
Referenced by jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::next_best_price(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
template<typename compare_t > std::size_t jb::itch5::array_based_book_side< compare_t >::relative_worst_top_level () const inline private
Returns
relative position of the worst valid price at top_levels
Definition at line 429 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::max_size_, jb::itch5::array_based_book_side< compare_t >::px_inside_, and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by jb::itch5::array_based_book_side< compare_t >::test_relative_worst_top_level(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
template<typename compare_t > void jb::itch5::array_based_book_side< compare_t >::test_move_top_to_bottom (price4_t const & px) inline
Definition at line 333 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom().
template<typename compare_t > auto jb::itch5::array_based_book_side< compare_t >::test_price_to_relative (price4_t const & px) const inline
Testing hooks to increase coverage.
Definition at line 325 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::price_to_relative().
template<typename compare_t > auto jb::itch5::array_based_book_side< compare_t >::test_relative_worst_top_level () const inline
Definition at line 329 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::relative_worst_top_level().
template<typename compare_t > std::size_t jb::itch5::array_based_book_side< compare_t >::top_levels_count () const inline private
Returns
number of valid prices (>0) at top_levels_
Definition at line 444 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::empty_quote(), jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::px_inside_, and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by jb::itch5::array_based_book_side< compare_t >::count(), and jb::itch5::array_based_book_side< compare_t >::get_counts().
template<typename compare_t > half_quote jb::itch5::array_based_book_side< compare_t >::worst_quote () const inline
Returns
the worst bid price and quantity. Check if the side is empty first (return empty_quote in this case) The worst price is at the bottom_levels (if not empty), at the top_levels otherwise.
Definition at line 103 of file array_based_order_book.hpp.
References jb::itch5::array_based_book_side< compare_t >::bottom_levels_, jb::itch5::array_based_book_side< compare_t >::empty_quote(), jb::itch5::array_based_book_side< compare_t >::px_inside_, jb::itch5::array_based_book_side< compare_t >::relative_to_price(), jb::itch5::array_based_book_side< compare_t >::relative_worst_top_level(), and jb::itch5::array_based_book_side< compare_t >::top_levels_.
Referenced by BOOST_AUTO_TEST_CASE().
Member Data Documentation
template<typename compare_t > compare_t jb::itch5::array_based_book_side< compare_t >::better_ private
function object for inequality comparison of template parameter type.
if better_(p1,p2) is true means p1 is strictly a better price than p2
Definition at line 581 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::check_better(), jb::itch5::array_based_book_side< compare_t >::empty_quote(), jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices(), jb::itch5::array_based_book_side< compare_t >::move_bottom_to_top(), jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), and jb::itch5::array_based_book_side< compare_t >::relative_to_price().
template<typename compare_t > std::map<price4_t, int, compare_t> jb::itch5::array_based_book_side< compare_t >::bottom_levels_ private
the worst (tail) absolute prices and quantity
Definition at line 590 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::count(), jb::itch5::array_based_book_side< compare_t >::get_counts(), jb::itch5::array_based_book_side< compare_t >::move_bottom_to_top(), jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
template<typename compare_t > std::size_t jb::itch5::array_based_book_side< compare_t >::max_size_ private
top_levels_ max size
Definition at line 584 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::get_limit_top_prices(), jb::itch5::array_based_book_side< compare_t >::relative_to_price(), and jb::itch5::array_based_book_side< compare_t >::relative_worst_top_level().
template<typename compare_t > price4_t jb::itch5::array_based_book_side< compare_t >::px_begin_top_ private
one absolute price past-the-worst price in top_levels_ range
Definition at line 596 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::get_limits(), jb::itch5::array_based_book_side< compare_t >::move_bottom_to_top(), jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::price_to_relative(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), and jb::itch5::array_based_book_side< compare_t >::relative_to_price().
template<typename compare_t > price4_t jb::itch5::array_based_book_side< compare_t >::px_end_top_ private
absolute price at the inside
Definition at line 599 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::get_limits(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), and jb::itch5::array_based_book_side< compare_t >::relative_to_price().
template<typename compare_t > price4_t jb::itch5::array_based_book_side< compare_t >::px_inside_ private
better absolute price of top_levels_ range
Definition at line 593 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::best_quote(), jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::next_best_price(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), jb::itch5::array_based_book_side< compare_t >::relative_worst_top_level(), jb::itch5::array_based_book_side< compare_t >::top_levels_count(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
template<typename compare_t > std::vector<int> jb::itch5::array_based_book_side< compare_t >::top_levels_ private
the best relative prices and quantity
Definition at line 587 of file array_based_order_book.hpp.
Referenced by jb::itch5::array_based_book_side< compare_t >::add_order(), jb::itch5::array_based_book_side< compare_t >::best_quote(), jb::itch5::array_based_book_side< compare_t >::move_bottom_to_top(), jb::itch5::array_based_book_side< compare_t >::move_top_to_bottom(), jb::itch5::array_based_book_side< compare_t >::next_best_price(), jb::itch5::array_based_book_side< compare_t >::reduce_order(), jb::itch5::array_based_book_side< compare_t >::relative_worst_top_level(), jb::itch5::array_based_book_side< compare_t >::top_levels_count(), and jb::itch5::array_based_book_side< compare_t >::worst_quote().
The documentation for this class was generated from the following file:
jb/itch5/array_based_order_book.hpp