JayBeams: jb::itch5::testing Namespace Reference
jb::itch5::testing Namespace Reference
Functions used in testing jb::itch5 entities.
Functions
std::chrono::nanoseconds expected_ts ()
Return the expected timestamp for all the test messages.
std::pair< char const *, std::size_t > message_header ()
std::pair< char const *, std::size_t > add_order ()
std::pair< char const *, std::size_t > add_order_mpid ()
std::pair< char const *, std::size_t > broken_trade ()
std::pair< char const *, std::size_t > cross_trade ()
std::pair< char const *, std::size_t > ipo_quoting_period_update ()
std::pair< char const *, std::size_t > market_participant_position ()
std::pair< char const *, std::size_t > mwcb_breach ()
std::pair< char const *, std::size_t > mwcb_decline_level ()
std::pair< char const *, std::size_t > net_order_imbalance_indicator ()
std::pair< char const *, std::size_t > order_cancel ()
std::pair< char const *, std::size_t > order_delete ()
std::pair< char const *, std::size_t > order_executed ()
std::pair< char const *, std::size_t > order_executed_price ()
std::pair< char const *, std::size_t > order_replace ()
std::pair< char const *, std::size_t > reg_sho_restriction ()
std::pair< char const *, std::size_t > stock_directory ()
std::pair< char const *, std::size_t > stock_trading_action ()
std::pair< char const *, std::size_t > system_event ()
std::pair< char const *, std::size_t > trade ()
std::vector< char > create_message (int message_type, jb::itch5::timestamp ts, std::size_t total_size)
Generate test messages with a more-or-less valid header.
stock_directory_message create_stock_directory (char const *symbol)
Create a dummy jb::itch5::stock_directory_message for testing.
Detailed Description
Functions used in testing jb::itch5 entities.
Function Documentation
add_order()
std::pair< char const *, std::size_t > jb::itch5::testing::add_order ()
Definition at line 33 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
add_order_mpid()
std::pair< char const *, std::size_t > jb::itch5::testing::add_order_mpid ()
Definition at line 47 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
broken_trade()
std::pair< char const *, std::size_t > jb::itch5::testing::broken_trade ()
Definition at line 62 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
create_message()
std::vector< char > jb::itch5::testing::create_message (int message_type, jb::itch5::timestamp ts, std::size_t total_size)
Generate test messages with a more-or-less valid header.
For most tests we only need messages with a valid timestamp and message type and a known length. This is a simple function to generate such messages.
Definition at line 287 of file data.cpp.
References jb::itch5::protocol::header_size, jb::itch5::protocol::max_message_size, and jb::itch5::encoder< validate, T >::w().
Referenced by BOOST_AUTO_TEST_CASE().
create_stock_directory()
stock_directory_message jb::itch5::testing::create_stock_directory (char const * symbol)
Create a dummy jb::itch5::stock_directory_message for testing.
Definition at line 7 of file messages.cpp.
References jb::itch5::stock_directory_message::message_type.
Referenced by BOOST_AUTO_TEST_CASE().
cross_trade()
std::pair< char const *, std::size_t > jb::itch5::testing::cross_trade ()
Definition at line 72 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
expected_ts()
std::chrono::nanoseconds jb::itch5::testing::expected_ts ()
Return the expected timestamp for all the test messages.
Definition at line 19 of file data.cpp.
Referenced by BOOST_AUTO_TEST_CASE().
ipo_quoting_period_update()
std::pair< char const *, std::size_t > jb::itch5::testing::ipo_quoting_period_update ()
Definition at line 87 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
market_participant_position()
std::pair< char const *, std::size_t > jb::itch5::testing::market_participant_position ()
Definition at line 100 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
message_header()
std::pair< char const *, std::size_t > jb::itch5::testing::message_header ()
Definition at line 25 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
mwcb_breach()
std::pair< char const *, std::size_t > jb::itch5::testing::mwcb_breach ()
Definition at line 113 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
mwcb_decline_level()
std::pair< char const *, std::size_t > jb::itch5::testing::mwcb_decline_level ()
Definition at line 122 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
net_order_imbalance_indicator()
std::pair< char const *, std::size_t > jb::itch5::testing::net_order_imbalance_indicator ()
Definition at line 134 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
order_cancel()
std::pair< char const *, std::size_t > jb::itch5::testing::order_cancel ()
Definition at line 154 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
order_delete()
std::pair< char const *, std::size_t > jb::itch5::testing::order_delete ()
Definition at line 165 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
order_executed()
std::pair< char const *, std::size_t > jb::itch5::testing::order_executed ()
Definition at line 175 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
order_executed_price()
std::pair< char const *, std::size_t > jb::itch5::testing::order_executed_price ()
Definition at line 188 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
order_replace()
std::pair< char const *, std::size_t > jb::itch5::testing::order_replace ()
Definition at line 203 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
reg_sho_restriction()
std::pair< char const *, std::size_t > jb::itch5::testing::reg_sho_restriction ()
Definition at line 218 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
stock_directory()
std::pair< char const *, std::size_t > jb::itch5::testing::stock_directory ()
Definition at line 228 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
stock_trading_action()
std::pair< char const *, std::size_t > jb::itch5::testing::stock_trading_action ()
Definition at line 250 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().
system_event()
std::pair< char const *, std::size_t > jb::itch5::testing::system_event ()
Definition at line 262 of file data.cpp.
References JB_ITCH5_TEST_HEADER, and jb::testing::defaults::size.
Referenced by BOOST_AUTO_TEST_CASE().
trade()
std::pair< char const *, std::size_t > jb::itch5::testing::trade ()
Definition at line 271 of file data.cpp.
References JB_ITCH5_TEST_HEADER.
Referenced by BOOST_AUTO_TEST_CASE().