JayBeams: jb/itch5/ut_order_book.cpp File Reference
ut_order_book.cpp File Reference
#include <jb/itch5/order_book.hpp>
#include <boost/test/unit_test.hpp>
Functions
BOOST_AUTO_TEST_CASE (order_book_trivial)
BOOST_AUTO_TEST_CASE (order_book_buy)
BOOST_AUTO_TEST_CASE (order_book_sell)
BOOST_AUTO_TEST_CASE (order_book_buy_errors)
BOOST_AUTO_TEST_CASE (order_book_sell_errors)
Function Documentation
BOOST_AUTO_TEST_CASE() [1/5]
BOOST_AUTO_TEST_CASE (order_book_trivial)
Test:
Verify that jb::itch5::order_book<jb::itch5::map_price> works as expected.
Definition at line 9 of file ut_order_book.cpp.
References jb::itch5::order_book< book_type >::best_bid(), jb::itch5::order_book< book_type >::best_offer(), jb::itch5::order_book< book_type >::get_book_depth(), jb::itch5::order_book< book_type >::worst_bid(), and jb::itch5::order_book< book_type >::worst_offer().
BOOST_AUTO_TEST_CASE() [2/5]
BOOST_AUTO_TEST_CASE (order_book_buy)
Test:
Verify that the buy side of jb::itch5::order_book<jb::itch5::map_price> works as expected.
Definition at line 33 of file ut_order_book.cpp.
References jb::itch5::order_book< book_type >::best_bid(), jb::itch5::order_book< book_type >::best_offer(), jb::itch5::order_book< book_type >::get_book_depth(), jb::itch5::order_book< book_type >::handle_add_order(), jb::itch5::order_book< book_type >::handle_order_reduced(), jb::itch5::order_book< book_type >::worst_bid(), and jb::itch5::order_book< book_type >::worst_offer().
BOOST_AUTO_TEST_CASE() [3/5]
BOOST_AUTO_TEST_CASE (order_book_sell)
Test:
Verity that the sell side of jb::itch5::order_book<jb::itch5::map_price> works as expected.
Definition at line 139 of file ut_order_book.cpp.
References jb::itch5::order_book< book_type >::best_bid(), jb::itch5::order_book< book_type >::best_offer(), jb::itch5::order_book< book_type >::get_book_depth(), jb::itch5::order_book< book_type >::handle_add_order(), jb::itch5::order_book< book_type >::handle_order_reduced(), jb::itch5::order_book< book_type >::worst_bid(), and jb::itch5::order_book< book_type >::worst_offer().
BOOST_AUTO_TEST_CASE() [4/5]
BOOST_AUTO_TEST_CASE (order_book_buy_errors)
Test:
Verify that the buy side of jb::itch5::order_book<jb::itch5::map_price> handles errors as expected.
Definition at line 247 of file ut_order_book.cpp.
References jb::itch5::order_book< book_type >::best_bid(), jb::itch5::order_book< book_type >::handle_add_order(), and jb::itch5::order_book< book_type >::handle_order_reduced().
BOOST_AUTO_TEST_CASE() [5/5]
BOOST_AUTO_TEST_CASE (order_book_sell_errors)
Test:
Verify that the sell side of jb::itch5::order_book<jb::itch5::map_price> handles errors as expected.
Definition at line 279 of file ut_order_book.cpp.
References jb::itch5::order_book< book_type >::best_offer(), jb::itch5::order_book< book_type >::handle_add_order(), and jb::itch5::order_book< book_type >::handle_order_reduced().