JayBeams: jb/itch5/ut_compute_book.cpp File Reference
ut_compute_book.cpp File Reference
#include <jb/itch5/compute_book.hpp>
#include <jb/itch5/testing/data.hpp>
#include <jb/itch5/testing/messages.hpp>
#include <jb/itch5/trade_message.hpp>
#include <jb/as_hhmmss.hpp>
#include <skye/mock_function.hpp>
#include <boost/test/unit_test.hpp>
#include <algorithm>
#include <thread>
Namespaces
jb
The top-level namespace for the JayBeams library.
jb::itch5
Contains classes and functions to parse NASDAQ ITCH-5.0 messages, more information about ITCH-5.0 can be found at: http://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHSpecification.pdf.
jb::itch5::testing
Functions used in testing jb::itch5 entities.
Macros
#define BUY testing::BUY
#define SELL testing::SELL
Functions
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_add_order_message_buy (based_order_book &bk)
Test compute book based on book type.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_add_order_message_sell (based_order_book &bk)
Test compute book based on book type.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_increase_coverage (based_order_book &bk)
Test compute book increase coverage.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_edge_cases (based_order_book &bk)
Test compute book edge cases.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_reduction_edge_cases (based_order_book &bk)
Test compute book reduction edge cases.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_replace_edge_cases (based_order_book &bk)
Test compute book replace edge cases.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_order_executed_message (based_order_book &bk)
Test compute book order execute message.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_order_replace_message (based_order_book bk)
Test compute book order replace message.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_order_cancel_message (based_order_book &bk)
Test compute book order cancel message.
template<typename based_order_book >
void jb::itch5::testing::test_compute_book_stock_directory_message (based_order_book &bk)
Test compute book stock directory message.
BOOST_AUTO_TEST_CASE (compute_book_add_order_message)
BOOST_AUTO_TEST_CASE (compute_book_increase_coverage)
BOOST_AUTO_TEST_CASE (compute_book_add_order_message_edge_cases)
BOOST_AUTO_TEST_CASE (compute_book_reduction_edge_cases)
BOOST_AUTO_TEST_CASE (compute_book_replace_edge_cases)
BOOST_AUTO_TEST_CASE (compute_book_order_executed_message)
BOOST_AUTO_TEST_CASE (compute_book_order_replace_message)
BOOST_AUTO_TEST_CASE (compute_book_order_cancel_message)
BOOST_AUTO_TEST_CASE (compute_book_stock_directory_message)
BOOST_AUTO_TEST_CASE (compute_book_book_update_operators)
Variables
buy_sell_indicator_t const jb::itch5::testing::BUY (u'B')
buy_sell_indicator_t const jb::itch5::testing::SELL (u'S')
Macro Definition Documentation
#define BUY testing::BUY
Referenced by jb::itch5::testing::test_generate_inside_basic().
#define SELL testing::SELL
Referenced by jb::itch5::testing::test_generate_inside_basic().
Function Documentation
BOOST_AUTO_TEST_CASE (compute_book_add_order_message)
Test:
Verify compute book handle_message works as expected for add_order_message.
Definition at line 962 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_add_order_message_buy(), and jb::itch5::testing::test_compute_book_add_order_message_sell().
BOOST_AUTO_TEST_CASE (compute_book_increase_coverage)
Test:
Increase code coverage in jb::itch5::compute_book
Definition at line 977 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_increase_coverage().
BOOST_AUTO_TEST_CASE (compute_book_add_order_message_edge_cases)
Test:
Increase code coverage in jb::itch5::compute_book::handle_message for add_order_message.
Definition at line 989 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_edge_cases().
BOOST_AUTO_TEST_CASE (compute_book_reduction_edge_cases)
Test:
Increase code coverage in jb::itch5::compute_book::handle_order_reduction
Definition at line 1001 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_reduction_edge_cases().
BOOST_AUTO_TEST_CASE (compute_book_replace_edge_cases)
Test:
Increase code coverage for order_replace_message
Definition at line 1012 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_replace_edge_cases().
BOOST_AUTO_TEST_CASE (compute_book_order_executed_message)
Test:
Verify that jb::itch5::compute_book::handle_message works as expected for order_executed_message BUY & SELL.
Definition at line 1024 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_order_executed_message().
BOOST_AUTO_TEST_CASE (compute_book_order_replace_message)
Test:
Verify that jb::itch5::compute_book::handle_message works as expected for order_replace_message BUY & SELL.
Definition at line 1036 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_order_replace_message().
BOOST_AUTO_TEST_CASE (compute_book_order_cancel_message)
Test:
Verify that jb::itch5::compute_book::handle_message works as expected for order_cancel_message and order_delete_message, both sides.
Definition at line 1048 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_order_cancel_message().
BOOST_AUTO_TEST_CASE (compute_book_stock_directory_message)
Test:
Verify that jb::itch5::compute_book::handle_message works as expected for stock_directory_message.
Definition at line 1060 of file ut_compute_book.cpp.
References jb::itch5::testing::test_compute_book_stock_directory_message().
BOOST_AUTO_TEST_CASE (compute_book_book_update_operators)
Test:
Verify that jb::itch5::book_update operators work as expected.
Definition at line 1072 of file ut_compute_book.cpp.
References jb::itch5::testing::BUY, and jb::itch5::testing::SELL.